# Generated by Django 2.2.1 on 2019-06-01 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubricas', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contrasenna', models.CharField(default='inseguroxd', max_length=10)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso')),
            ],
            options={
                'verbose_name_plural': 'Evaluadores',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('0', 'Cerrada'), ('1', 'Abierta')], default='1', max_length=1)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso')),
                ('evaluadores', models.ManyToManyField(to='evaluaciones.Evaluador')),
                ('rubrica', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rubricas.Rubrica')),
            ],
            options={
                'verbose_name_plural': 'Evaluaciones',
                'unique_together': {('curso', 'nombre')},
            },
        ),
    ]
