# Generated by Django 2.2.1 on 2019-06-02 00:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubricas', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('0', 'Cerrada'), ('1', 'Abierta')], default='1', max_length=1)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso')),
                ('evaluadores', models.ManyToManyField(to='usuarios.Evaluador')),
                ('rubrica', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rubricas.Rubrica')),
            ],
            options={
                'verbose_name_plural': 'Evaluaciones',
                'unique_together': {('curso', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Directory', models.CharField(default='/evaluaciones/storage/', max_length=60)),
                ('release_date', models.DateTimeField(default=datetime.datetime.now)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Equipo')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.Evaluacion')),
            ],
        ),
    ]
