# Generated by Django 2.2 on 2019-06-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Integrante',
        ),
    ]
