# Generated by Django 2.2 on 2019-04-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_evaluadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('sex_number', models.IntegerField()),
                ('año', models.IntegerField()),
                ('semester', models.CharField(choices=[('1', 'Otoño'), ('2', 'Primavera'), ('3', 'Verano')], default='2', max_length=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='Evaluadores',
            new_name='Evaluador',
        ),
        migrations.RenameModel(
            old_name='Integrantes',
            new_name='Integrante',
        ),
        migrations.AlterModelOptions(
            name='evaluador',
            options={'verbose_name_plural': 'Evaluadores'},
        ),
    ]
