# Generated by Django 2.2 on 2019-05-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_auto_20190520_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='año',
            new_name='anno',
        ),
        migrations.RemoveField(
            model_name='evaluador',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='evaluador',
            name='contrasenna',
            field=models.CharField(default='inseguroxd', max_length=10),
        ),
        migrations.AlterField(
            model_name='evaluador',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.Curso'),
        ),
    ]
