# Generated by Django 2.2 on 2019-05-24 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_auto_20190522_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso'),
        ),
        migrations.AlterField(
            model_name='evaluador',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso'),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
