# Generated by Django 2.2.1 on 2019-05-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('sex_number', models.IntegerField()),
                ('anno', models.IntegerField()),
                ('semester', models.IntegerField(choices=[(1, 'Otoño'), (2, 'Primavera'), (3, 'Verano')], default='2')),
            ],
        ),
    ]
