# Generated by Django 2.2 on 2019-06-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estudiantes', models.ManyToManyField(to='cursos.Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='equipos',
            field=models.ManyToManyField(to='cursos.Equipo'),
        ),
    ]
