# Generated by Django 2.2 on 2019-06-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_evaluador_curso'),
        ('cursos', '0002_auto_20190601_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='evaluadores',
            field=models.ManyToManyField(to='usuarios.Evaluador'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('codigo', 'sex_number', 'anno', 'semester')},
        ),
    ]
