# Generated by Django 2.2 on 2019-06-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_evaluador_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluador',
            name='curso',
        ),
    ]
