# Generated by Django 2.2.1 on 2019-06-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_evaluador_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluador',
            name='email',
        ),
    ]
