# Generated by Django 2.2.1 on 2019-06-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_evaluador_curso'),
        ('usuarios', '0003_remove_evaluador_email'),
    ]

    operations = [
    ]
