# Generated by Django 2.2.1 on 2019-05-28 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('durationMin', models.IntegerField(default=0)),
                ('durationMax', models.IntegerField()),
                ('Directory', models.CharField(default='/rubricas/storage/', max_length=60)),
                ('release_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
