# Generated by Django 2.1.5 on 2019-05-20 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubricas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='Directory',
            field=models.CharField(default='/rubricas/storage/', max_length=60),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
